#!/usr/bin/env python3
"""Q7 harness: spawn StdioEcho, drive binary length-framed protobuf over its stdin/stdout,
assert round-trip integrity for both unary and server-streaming patterns."""
import struct, subprocess, sys, os

# spike_pb2 is generated by protoc --python_out in the stdio CI job (or locally via generate.sh)
sys.path.insert(0, os.path.dirname(__file__))
import spike_pb2 as pb

exe_suffix = ".exe" if os.name == "nt" else ""
server_bin = os.path.join(".build", "debug", "StdioEcho" + exe_suffix)
print(f"server={server_bin}", flush=True)

if not os.path.exists(server_bin):
    print(f"FAIL: binary not found: {server_bin}"); sys.exit(10)

# Binary pipes; stderr inherited so server's logErr() appears in CI logs.
p = subprocess.Popen([server_bin], stdin=subprocess.PIPE, stdout=subprocess.PIPE)

def send(env):
    data = env.SerializeToString()
    p.stdin.write(struct.pack(">I", len(data)) + data)
    p.stdin.flush()

def recv():
    hdr = p.stdout.read(4)
    if len(hdr) < 4: return None
    (n,) = struct.unpack(">I", hdr)
    body = b""
    while len(body) < n:
        chunk = p.stdout.read(n - len(body))
        if not chunk: return None
        body += chunk
    e = pb.Envelope(); e.ParseFromString(body); return e

try:
    # Q7a: unary echo
    req = pb.EchoRequest(message="hello", count=1)
    send(pb.Envelope(id=1, kind=pb.Envelope.REQUEST, method="echo",
                     payload=req.SerializeToString()))
    r = recv()
    if r is None or r.kind != pb.Envelope.RESPONSE:
        print(f"FAIL: no RESPONSE (Q7 unary)"); p.kill(); sys.exit(20)
    resp = pb.EchoResponse(); resp.ParseFromString(r.payload)
    if resp.message != "echo: hello":
        print(f"FAIL: unary mismatch '{resp.message}'"); p.kill(); sys.exit(21)
    print("STDIO_UNARY_OK", resp.message, flush=True)

    # Q7b: server-streaming
    send(pb.Envelope(id=2, kind=pb.Envelope.REQUEST, method="stream",
                     payload=pb.EchoRequest(message="stream", count=5).SerializeToString()))
    items = 0
    while True:
        e = recv()
        if e is None:
            print("FAIL: stream truncated (Q7 streaming)"); p.kill(); sys.exit(22)
        if e.kind == pb.Envelope.STREAM_ITEM:
            items += 1
        elif e.kind == pb.Envelope.STREAM_END:
            break
    if items != 5:
        print(f"FAIL: stream items {items} != 5"); p.kill(); sys.exit(23)
    print("STDIO_STREAM_OK", items, flush=True)

    # graceful shutdown
    send(pb.Envelope(id=3, kind=pb.Envelope.REQUEST, method="shutdown"))
    p.stdin.close()
    try: p.wait(timeout=10)
    except Exception: p.kill()

except Exception as e:
    print(f"FAIL: unexpected error: {e}"); p.kill(); raise

print("STDIO_ALL_OK")
