// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: spike.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - spike.v1.Echo

/// Namespace containing generated types for the "spike.v1.Echo" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Spike_V1_Echo {
    /// Service descriptor for the "spike.v1.Echo" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spike.v1.Echo")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "UnaryEcho" metadata.
        public enum UnaryEcho {
            /// Request type for "UnaryEcho".
            public typealias Input = Spike_V1_EchoRequest
            /// Response type for "UnaryEcho".
            public typealias Output = Spike_V1_EchoResponse
            /// Descriptor for "UnaryEcho".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spike.v1.Echo"),
                method: "UnaryEcho"
            )
        }
        /// Namespace for "StreamEcho" metadata.
        public enum StreamEcho {
            /// Request type for "StreamEcho".
            public typealias Input = Spike_V1_EchoRequest
            /// Response type for "StreamEcho".
            public typealias Output = Spike_V1_EchoResponse
            /// Descriptor for "StreamEcho".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "spike.v1.Echo"),
                method: "StreamEcho"
            )
        }
        /// Descriptors for all methods in the "spike.v1.Echo" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            UnaryEcho.descriptor,
            StreamEcho.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "spike.v1.Echo" service.
    public static let spike_v1_Echo = GRPCCore.ServiceDescriptor(fullyQualifiedService: "spike.v1.Echo")
}

// MARK: spike.v1.Echo (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo {
    /// Streaming variant of the service protocol for the "spike.v1.Echo" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "UnaryEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q2: unary round-trip
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Spike_V1_EchoRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Spike_V1_EchoResponse` messages.
        func unaryEcho(
            request: GRPCCore.StreamingServerRequest<Spike_V1_EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse>

        /// Handle the "StreamEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q3: server-streaming (mirrors Star's progress stream)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Spike_V1_EchoRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Spike_V1_EchoResponse` messages.
        func streamEcho(
            request: GRPCCore.StreamingServerRequest<Spike_V1_EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse>
    }

    /// Service protocol for the "spike.v1.Echo" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Spike_V1_Echo.StreamingServiceProtocol {
        /// Handle the "UnaryEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q2: unary round-trip
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Spike_V1_EchoResponse` message.
        func unaryEcho(
            request: GRPCCore.ServerRequest<Spike_V1_EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Spike_V1_EchoResponse>

        /// Handle the "StreamEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q3: server-streaming (mirrors Star's progress stream)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Spike_V1_EchoResponse` messages.
        func streamEcho(
            request: GRPCCore.ServerRequest<Spike_V1_EchoRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse>
    }

    /// Simple service protocol for the "spike.v1.Echo" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Spike_V1_Echo.ServiceProtocol {
        /// Handle the "UnaryEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q2: unary round-trip
        ///
        /// - Parameters:
        ///   - request: A `Spike_V1_EchoRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Spike_V1_EchoResponse` to respond with.
        func unaryEcho(
            request: Spike_V1_EchoRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Spike_V1_EchoResponse

        /// Handle the "StreamEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q3: server-streaming (mirrors Star's progress stream)
        ///
        /// - Parameters:
        ///   - request: A `Spike_V1_EchoRequest` message.
        ///   - response: A response stream of `Spike_V1_EchoResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func streamEcho(
            request: Spike_V1_EchoRequest,
            response: GRPCCore.RPCWriter<Spike_V1_EchoResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Spike_V1_Echo.Method.UnaryEcho.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Spike_V1_EchoRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Spike_V1_EchoResponse>(),
            handler: { request, context in
                try await self.unaryEcho(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Spike_V1_Echo.Method.StreamEcho.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Spike_V1_EchoRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Spike_V1_EchoResponse>(),
            handler: { request, context in
                try await self.streamEcho(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo.ServiceProtocol {
    public func unaryEcho(
        request: GRPCCore.StreamingServerRequest<Spike_V1_EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse> {
        let response = try await self.unaryEcho(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func streamEcho(
        request: GRPCCore.StreamingServerRequest<Spike_V1_EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse> {
        let response = try await self.streamEcho(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo.SimpleServiceProtocol {
    public func unaryEcho(
        request: GRPCCore.ServerRequest<Spike_V1_EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Spike_V1_EchoResponse> {
        return GRPCCore.ServerResponse<Spike_V1_EchoResponse>(
            message: try await self.unaryEcho(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func streamEcho(
        request: GRPCCore.ServerRequest<Spike_V1_EchoRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse> {
        return GRPCCore.StreamingServerResponse<Spike_V1_EchoResponse>(
            metadata: [:],
            producer: { writer in
                try await self.streamEcho(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: spike.v1.Echo (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo {
    /// Generated client protocol for the "spike.v1.Echo" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "UnaryEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q2: unary round-trip
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - serializer: A serializer for `Spike_V1_EchoRequest` messages.
        ///   - deserializer: A deserializer for `Spike_V1_EchoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func unaryEcho<Result>(
            request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<Spike_V1_EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Spike_V1_EchoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Spike_V1_EchoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "StreamEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q3: server-streaming (mirrors Star's progress stream)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - serializer: A serializer for `Spike_V1_EchoRequest` messages.
        ///   - deserializer: A deserializer for `Spike_V1_EchoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func streamEcho<Result>(
            request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<Spike_V1_EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Spike_V1_EchoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Spike_V1_EchoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "spike.v1.Echo" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "UnaryEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q2: unary round-trip
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - serializer: A serializer for `Spike_V1_EchoRequest` messages.
        ///   - deserializer: A deserializer for `Spike_V1_EchoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func unaryEcho<Result>(
            request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<Spike_V1_EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Spike_V1_EchoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Spike_V1_EchoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Spike_V1_Echo.Method.UnaryEcho.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "StreamEcho" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Q3: server-streaming (mirrors Star's progress stream)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
        ///   - serializer: A serializer for `Spike_V1_EchoRequest` messages.
        ///   - deserializer: A deserializer for `Spike_V1_EchoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func streamEcho<Result>(
            request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
            serializer: some GRPCCore.MessageSerializer<Spike_V1_EchoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Spike_V1_EchoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Spike_V1_EchoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Spike_V1_Echo.Method.StreamEcho.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo.ClientProtocol {
    /// Call the "UnaryEcho" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Q2: unary round-trip
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unaryEcho<Result>(
        request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Spike_V1_EchoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unaryEcho(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Spike_V1_EchoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Spike_V1_EchoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StreamEcho" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Q3: server-streaming (mirrors Star's progress stream)
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Spike_V1_EchoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamEcho<Result>(
        request: GRPCCore.ClientRequest<Spike_V1_EchoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Spike_V1_EchoResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.streamEcho(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Spike_V1_EchoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Spike_V1_EchoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Spike_V1_Echo.ClientProtocol {
    /// Call the "UnaryEcho" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Q2: unary round-trip
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unaryEcho<Result>(
        _ message: Spike_V1_EchoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Spike_V1_EchoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Spike_V1_EchoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.unaryEcho(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StreamEcho" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Q3: server-streaming (mirrors Star's progress stream)
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamEcho<Result>(
        _ message: Spike_V1_EchoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Spike_V1_EchoResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Spike_V1_EchoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.streamEcho(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}